### ISSUE TITLE
Heroku suspended

### ISSUE THREAD

**Issue by ahmed98Osama** [BlackBox-cmd/Freak-mirrorbot#2]
This is a notice to inform you that your Heroku app, lazzzybott, has been suspended.

**Comment by BlackBox-cmd** [comment]
> This is a notice to inform you that your Heroku app, lazzzybott, has been suspended.

My Bots Are Fine . Maybe It's Your Problem.

**Comment by ahmed98Osama** [comment]
old one works fine 

but when i try to create a new one  i get suspended
